name: Build Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Install PyInstaller
          pip install -r requirements.txt  # Install your app's dependencies

      - name: Build executable
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            pyinstaller --onefile your_script.py  # Replace with your script name
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile your_script.py  # Replace with your script name
          fi

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: dist/your_script  # Adjust based on your script name

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: executable-ubuntu-latest  # For Linux
          path: ./artifacts/linux  # Path to save the Linux artifact

      - name: Download Executable (Windows)
        uses: actions/download-artifact@v2
        with:
          name: executable-windows-latest  # For Windows
          path: ./artifacts/windows  # Path to save the Windows artifact
