name: Build Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Install PyInstaller
          pip install -r app/requirements.txt  # Install your app's dependencies

      - name: Build executable (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile app/ticket_app.py

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          pyinstaller --onefile app/ticket_app.py

      - name: Move Executable to bin (Linux)
        if: runner.os == 'Linux'
        run: mv dist/ticket_app bin/

      - name: Move Executable to bin (Windows)
        if: runner.os == 'Windows'
        run: mv dist/ticket_app.exe bin/

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: backup_remover-bin-${{ runner.os }}
          path: bin/ticket_app  # Adjust based on your script name

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: backup_remover-bin-${{ runner.os }}
          path: bin/ticket_app.exe  # Adjust based on your script name
